apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-task-sync-and-wait
spec:
  params:
    - name: flags
      default: --
    - name: argocd-version
      description: The version of argocd to use
      default: v2.1.7
    - name: argocdServer
      description: The URL of the ArgoCD server
    - name: applicationName
      description: The name of the application to sync
    - name: applicationRevision
      description: The revision of the application to sync
      default: HEAD
  stepTemplate:
    envFrom:
      - secretRef:
          name: argocd-env-secret  # used for authentication (username/password or auth token)
  steps:
    - name: argocd-app-sync
      image: argoproj/argocd:$(params.argocd-version)
      script: |
        argocd login $(params.argocdServer) --grpc-web --grpc-web-root-path /argo-cd --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD
        argocd app sync $(params.applicationName) $(params.flags) --grpc-web-root-path /argo-cd --server $(params.argocdServer)
        argocd app wait $(params.applicationName) --health $(params.flags) --grpc-web-root-path /argo-cd --server $(params.argocdServer)
