---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image
spec:
  resources:
    inputs:
      - name: git-app-repo
        type: git
    outputs:
      - name: image-registry
        type: image
  params:
    - name: pathToDockerFile
      description: Path to Dockerfile
      default: Dockerfile
    - name: pathToContext
      description: The build context used by Kaniko
      default: /workspace/git-app-repo
    - name: dockerTag
      description: The tag of the built image
      default: latest
    - name: dockerImage
      description: The name of the built image
    - name: dockerNamespace
      description: The namespace of the built image

  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: "DOCKER_CONFIG"
          value: "/builder/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.pathToContext)/$(params.pathToDockerFile)
        - --destination=$(resources.outputs.image-registry.url)/$(params.dockerNamespace)/$(params.dockerImage):$(params.dockerTag)
        - --context=$(params.pathToContext)