kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: el-tekton-argocd-example-build-el-ingress
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/el-tekton-argocd-example-build-el`)
      services:
        - name: el-tekton-argocd-example-build-el
          port: 8080
          namespace: tekton-argocd-example
  tls:
    secretName: stiforr-com-tls